version: "3.8"

networks:
  currency:
    driver: bridge

services:
  app:
    networks:
      - currency
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    volumes:
      - .:/app
      
volumes:
  db: